### ISSUE TITLE
Doesn't work in the JVM

### ISSUE THREAD

**Issue by ianq22** [evansloan082/sports.py#5]
Hey there Package Maintainer,

Great library, cool concept. I keep trying to get this to work in Java but for some reason the JVM keeps complaining that it can't compile the library files. I was wondering if you knew of any way around this? I've tried compiling in other JVM languages like Kotlin and Ruby, but no luck. If you know of any ideas that could help I would appreciate it!

**Comment by evansloan** [comment]
Have you tried turning your JVM on and off?

**Comment by ianq22** [comment]
Hello Bevin,

I just tried this right now I deleted my /etc/ and my /boot/ directory and now my computer does not work. I think I'm going to need to speak to your manager because service like this is rude and frankly, unprofessional. I'm not sure what kind of clown show you think you're running here but I've hacked into numerous small restaurant websites in the Davenport, Iowa area and you just became my next target pal.

Don't mess with me I will end you son
