### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by TellTej** [evansloan082/sports.py#8]
I fixed the code, however, I am still receiving the error 

`ModuleNotFoundError: No module named 'sports'`

This is because the file is in Python 2.7

I saw the earlier issue, however, the video Is no longer available. Could you post it again?

**Comment by evansloan** [comment]
I'm not sure why/how the video was removed, but I no longer have the file on my computer. I don't really have a ton of time right now to make another so here's a link that should outline pretty much everything that was in the video.

[Python virtual environments](https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments)

After you setup the virtual environment and activate it, you should be able to install sports.py to your virtual environment with `pip install sports.py`

If you have any trouble let me know and I'll try to help you to the best of my ability.
